### ISSUE TITLE
Fix display of Maidenform Logo

### ISSUE THREAD

**Issue by herzog31** [hlxsites/maidenform#141]
- [ ] Ensure the Maidenform logo is correctly displayed, might be an SVG scaling issue
- [ ] Proposal and contribution to boilerplate to provide a generic solution to this issue

![Screenshot 2023-03-03 at 17 25 48](https://user-images.githubusercontent.com/4084418/222773859-8f5b31f9-5e13-4816-a537-d382e6ea9a9a.png)

**Comment by dicagno** [comment]
@herzog31 are you referring to the aliasing that is shown in the logo's borders?

**Comment by dicagno** [comment]
From the diff below, we can see that the svg `rect` corresponding to the "I" character in Maidenform logo is being hidden because of removal of `height` and `width` attributes from the svg symbol:
![Screenshot 2023-03-13 at 11 57 02](https://user-images.githubusercontent.com/5924009/224686871-17b5cb41-c6fe-43e9-a287-6f523b35dc87.png)

Lines causing the issue:
https://github.com/hlxsites/maidenform/blob/57b22398fe9e8edcaa4d132f63cbbd3e916e5c1a/scripts/lib-franklin.js#LL161-L162

Working on the fix. @herzog31 shall we open another PR for lib-franklin.js?

**Comment by herzog31** [comment]
@dicagno If you have capacity, contributing the fix back to the [boilerplate](https://github.com/adobe/helix-project-boilerplate) is a great idea 👍

**Comment by dicagno** [comment]
Created issue & linked PR to boilerplate: https://github.com/adobe/helix-project-boilerplate/issues/191
